FROM ghcr.io/astral-sh/uv:python{{pythonVersion}}-bookworm-slim

LABEL "com.javaaidev.llm-code-executor.description"="{{description}}"

ENV UV_COMPILE_BYTECODE=1

ADD ./app /app

WORKDIR /app
RUN uv sync